version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo 
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run dev

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: abcd

volumes:
  mongo-data:
